/**
 * Axiom CRM API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AxiomUser { 
    id: string;
    email: string;
    firstName: string;
    middleName?: string;
    lastName: string;
    pinType: string;
    pin: string;
    phoneNumber: string;
    insuranceNumber?: string;
    insuranceCardNumber?: string;
    isDataPrivacyAccepted: boolean;
    isAdvertisingSubscriptionAccepted: boolean;
    areGeneralTermsAccepted: boolean;
}