/**
 * Axiom CRM API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankPayment } from './bankPayment';
import { Customer } from './customer';
import { HealthClaimCase } from './healthClaimCase';

export interface CreateClaimRequest {
  applicantTypeId: number;
  applicant?: Customer;
  insuredPerson?: Customer;
  claimDate: Date;
  claimReasonId: number;
  insuranceCardNumber: string;
  paymentTypeId: number;
  bankPayment?: BankPayment;
  note: string;
  cases?: Array<HealthClaimCase>;
  preferredCommunicationChannel: number;
}
