/**
 * Axiom BROKER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HealthClaimDetail {
  claimId: number;
  claimDate: Date;
  pin?: string;
  insuranceNumber?: string;
  insuranceCardNumber?: string;
  insuredPersonName?: string;
  claimStatus?: string;
  approvedDate: Date;
  invoiceNumber?: string;
  servicesAmount?: string;
  approvedServicesAmount?: string;
  drugsAmount?: string;
  approvedDrugsAmount?: string;
  paymentDate: Date;
  currencyCode?: string;
  note?: string;
  approvedNote?: string;
  claimNumTr?: string;
  packageName?: string;
  packFranchServ?: string;
  parentInvoiceNumber?: string;
  parentCaseId: number;
}
