/**
 * Axiom CRM API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { HttpClient, HttpEvent, HttpHeaders, HttpResponse } from '@angular/common/http';
import { Injectable, Optional } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { Configuration } from '../configuration';
import { CardDetailsBody } from '../model/cardDetailsBody';
import { ListContractsResponse } from '../model/listContractsResponse';
import {
  ClaimCreateBody,
  CreateClaimResponse,
  GetCardDetailsResponse,
  IAxiomNom,
  ListClaimsByCardNumberResponse,
  ListClaimsResponse
} from '../model/models';

@Injectable()
export class HealthService {
  protected basePath = '/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() configuration: Configuration) {
    this.basePath = environment.apiUrl;

    if (configuration) {
      this.configuration = configuration;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Get health accident types
   * Get health accident types
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public healthAccidentTypes(observe?: 'body', reportProgress?: boolean): Observable<Array<IAxiomNom>>;
  public healthAccidentTypes(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Array<IAxiomNom>>>;
  public healthAccidentTypes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<IAxiomNom>>>;
  public healthAccidentTypes(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['text/plain', 'application/json', 'text/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<Array<IAxiomNom>>('get', `${this.basePath}/health/accidentTypes`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Get health claims
   * Get health claims
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public healthClaims(observe?: 'body', reportProgress?: boolean): Observable<ListClaimsResponse>;
  public healthClaims(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ListClaimsResponse>>;
  public healthClaims(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ListClaimsResponse>>;
  public healthClaims(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['text/plain', 'application/json', 'text/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<ListClaimsResponse>('get', `${this.basePath}/health/claims`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Get health claims by card number
   * Get health claims by card number
   * @param cardNumber
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public healthClaimsCardNumber(
    cardNumber: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ListClaimsByCardNumberResponse>;
  public healthClaimsCardNumber(
    cardNumber: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ListClaimsByCardNumberResponse>>;
  public healthClaimsCardNumber(
    cardNumber: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ListClaimsByCardNumberResponse>>;
  public healthClaimsCardNumber(
    cardNumber: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (cardNumber === null || cardNumber === undefined) {
      throw new Error('Required parameter cardNumber was null or undefined when calling healthClaimsCardnumber.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['text/plain', 'application/json', 'text/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<ListClaimsByCardNumberResponse>(
      'get',
      `${this.basePath}/health/claims/card/${encodeURIComponent(String(cardNumber))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get health contracts
   * Get health contracts
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public healthContracts(observe?: 'body', reportProgress?: boolean): Observable<ListContractsResponse>;
  public healthContracts(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ListContractsResponse>>;
  public healthContracts(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ListContractsResponse>>;
  public healthContracts(observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['text/plain', 'application/json', 'text/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<ListContractsResponse>('get', `${this.basePath}/health/contracts`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Get a details for a specific card by date and pin
   * Get a details for a specific card by date and pin
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public healthCardDetails(
    body?: CardDetailsBody,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<GetCardDetailsResponse>;
  public healthCardDetails(
    body?: CardDetailsBody,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<GetCardDetailsResponse>>;
  public healthCardDetails(
    body?: CardDetailsBody,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<GetCardDetailsResponse>>;
  public healthCardDetails(
    body?: CardDetailsBody,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['text/plain', 'application/json', 'text/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json', 'text/json', 'application/_*+json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<GetCardDetailsResponse>('post', `${this.basePath}/health/card/details`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }

  /**
   * Create health claim
   * Create health claim
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public healthClaimCreate(
    body?: ClaimCreateBody,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<CreateClaimResponse>;
  public healthClaimCreate(
    body?: ClaimCreateBody,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<CreateClaimResponse>>;
  public healthClaimCreate(
    body?: ClaimCreateBody,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<CreateClaimResponse>>;
  public healthClaimCreate(
    body?: ClaimCreateBody,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // authentication (Bearer) required
    if (this.configuration.apiKeys && this.configuration.apiKeys['Authorization']) {
      headers = headers.set('Authorization', this.configuration.apiKeys['Authorization']);
    }

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['text/plain', 'application/json', 'text/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json', 'text/json', 'application/_*+json'];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<CreateClaimResponse>('post', `${this.basePath}/health/claim/create`, {
      body: body,
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    });
  }
}
